name: fooderlich
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  platform: ^3.1.0
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  provider: ^6.0.0
  flutter_colorpicker: ^0.6.0
  intl: ^0.17.0
  uuid: ^3.0.4
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^2.0.13
  url_launcher: ^6.0.10  # A cross-platform library to help launch a URL.
  shared_preferences: ^2.0.7  # Wraps platform-specific persistent storage for simple data. AppCache uses this package to store the user login and onboarding state.
  # go_router: ^2.2.8  # for 'pageBuilder'
  go_router: ^3.0.0  # for 'builder'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
    - assets/fooderlich_assets/
